export const GET_AUTOPARTS = 'GET_AUTOPARTS'
export const CREATE_AUTOPART = 'CREATE_AUTOPART'
export const UPDATE_AUTOPART = 'UPDATE_AUTOPART'
export const UPDATE_AUTOPART_STATUS = 'UPDATE_AUTOPART_STATUS'
