services:
  app:
    build:
      target: node_server
      context: ../
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env
    networks:
      - internal
    volumes:
      - ../uploads:/app/uploads
    labels:
      - traefik.enable=false

  nginx:
    build:
      target: web_server
      context: ../
      dockerfile: Dockerfile
    restart: always
    networks:
      - internal
      - review
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${REVIEW_HOST}
      - traefik.port=80
      - traefik.docker.network=review
    depends_on:
      - app

networks:
  internal:
  review:
    external: true
    name: review
