export const GET_CONDPRICES = 'GET_CONDPRICES'
export const CREATE_CONDPRICE = 'CREATE_CONDPRICE'
export const UPDATE_CONDPRICE = 'UPDATE_CONDPRICE'
export const DELETE_CONDPRICE = 'DELETE_CONDPRICE'
