export const GET_DISKPAINTINGPRICES = 'GET_DISKPAINTINGPRICES'
export const CREATE_DISKPAINTINGPRICE = 'CREATE_DISKPAINTINGPRICE'
export const UPDATE_DISKPAINTINGPRICE = 'UPDATE_DISKPAINTINGPRICE'
export const DELETE_DISKPAINTINGPRICE = 'DELETE_DISKPAINTINGPRICE'
