export const GET_EMPLOYEES_DATA = 'GET_EMPLOYEES_DATA'
export const CREATE_EMPLOYEE_DATA = 'CREATE_EMPLOYEE_DATA'
export const UPDATE_EMPLOYEE_DATA = 'UPDATE_EMPLOYEE_DATA'
export const DELETE_EMPLOYEE_DATA = 'DELETE_EMPLOYEE_DATA'
