export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS'
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION'
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION'
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION'
