export const GET_POSITIONS = 'GET_POSITIONS'
export const CREATE_POSITION = 'CREATE_POSITION'
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const DELETE_POSITION = 'DELETE_POSITION'
export const ADD_DUTY = 'ADD_DUTY'
export const UPDATE_DUTY = 'UPDATE_DUTY'
export const DELETE_DUTY = 'DELETE_DUTY'
export const REORDER_DUTIES = 'REORDER_DUTIES'

