export const GET_SHINOMONTAZHPRICES = 'GET_SHINOMONTAZHPRICES'
export const CREATE_SHINOMONTAZHPRICE = 'CREATE_SHINOMONTAZHPRICE'
export const UPDATE_SHINOMONTAZHPRICE = 'UPDATE_SHINOMONTAZHPRICE'
export const DELETE_SHINOMONTAZHPRICE = 'DELETE_SHINOMONTAZHPRICE'
