export const GET_TYRES = 'GET_TYRES'
export const GET_TYRE = 'GET_TYRE'
export const CREATE_TYRE = 'CREATE_TYRE'
export const UPDATE_TYRE = 'UPDATE_TYRE'
export const UPDATE_TYRE_STATUS = 'UPDATE_TYRE_STATUS'
