export const GET_WASHPRICES = 'GET_WASHPRICES'
export const CREATE_WASHPRICE = 'CREATE_WASHPRICE'
export const UPDATE_WASHPRICE = 'UPDATE_WASHPRICE'
export const DELETE_WASHPRICE = 'DELETE_WASHPRICE'
