export const GET_WINDOWPRICES = 'GET_WINDOWPRICES'
export const CREATE_WINDOWPRICE = 'CREATE_WINDOWPRICE'
export const UPDATE_WINDOWPRICE = 'UPDATE_WINDOWPRICE'
export const DELETE_WINDOWPRICE = 'DELETE_WINDOWPRICE'
