#!/usr/bin/env node
/**
 * Generates TypeScript interfaces from the Mongoose schemas in server/model/*.js.
 *
 * Run: node scripts/generate-types.js  (also runs automatically before `yarn typecheck`)
 * Output: common/types/generated/<PascalCaseName>.ts - one file per model,
 * fully overwritten on every run. Don't hand-edit files in that directory.
 *
 * Why this exists: previously client/types/*.ts were hand-written copies of
 * the server's Mongoose schemas, kept "in sync by hand" - i.e. not actually
 * enforced. This reads each schema's *compiled* SchemaTypes at require-time
 * (Model.schema.paths), so the output reflects exactly what Mongoose will
 * read/write/return: fields added by plugins (e.g. mongoose-sequence's
 * autoincrement field), Mongoose's own implicit _id/__v, and enum constraints.
 *
 * What it can't infer on its own:
 *  - a bare `type: Array` field with no item schema/caster becomes `unknown[]`
 *    (Mongoose itself doesn't know the item type either - it defaults the
 *    caster to Mixed)
 *  - `Schema.Types.Mixed` fields become `unknown`
 * Add a one-line entry to OVERRIDES below when the real shape is known from
 * how the field is actually used but isn't inferable from the schema.
 */
require('@babel/register')({
  extensions: ['.js', '.jsx', '.es6', '.es', '.mjs', '.cjs', '.ts', '.tsx']
})

const fs = require('fs')
const path = require('path')

const MODEL_DIR = path.join(__dirname, '../server/model')
const OUT_DIR = path.join(__dirname, '../common/types/generated')

// Key = '<model file base name>.<field path>' (dot-joined for nested fields).
const OVERRIDES = {
  'employee.role': 'string[]',
  'employee.address': 'string[]'
}

function toPascalCase(fileBaseName) {
  // 'car.generation' -> 'CarGeneration', 'journalEntry' -> 'JournalEntry', 'User.model' -> 'User'
  return fileBaseName
    .replace(/\.model$/i, '')
    .split(/[.\-_]/)
    .filter(Boolean)
    .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
    .join('')
}

function scalarTsType(pathType) {
  switch (pathType.instance) {
    case 'String':
      return 'string'
    case 'Number':
      return 'number'
    case 'Boolean':
      return 'boolean'
    case 'Date':
      return 'string' // Dates serialize to an ISO string over JSON
    case 'ObjectId':
    case 'ObjectID':
      return 'string'
    case 'Map':
      return 'Record<string, unknown>'
    case 'Mixed':
    default:
      return 'unknown'
  }
}

// pathToTsType/fieldsToInline are mutually recursive (subdocument arrays
// nest fields which may themselves be subdocument arrays).
function pathToTsType(pathType, overrideKey) {
  if (OVERRIDES[overrideKey]) return OVERRIDES[overrideKey]

  if (pathType.enumValues && pathType.enumValues.length > 0) {
    return pathType.enumValues.map((v) => JSON.stringify(v)).join(' | ')
  }

  if (pathType.instance === 'Array') {
    if (pathType.schema) {
      // Array of subdocuments - recurse into the nested schema.
      // eslint-disable-next-line no-use-before-define
      return `Array<{ ${fieldsToInline(pathType.schema, overrideKey)} }>`
    }
    if (pathType.caster && pathType.caster.instance !== 'Mixed') {
      return `${scalarTsType(pathType.caster)}[]`
    }
    return 'unknown[]'
  }

  return scalarTsType(pathType)
}

function fieldsToInline(schema, parentKey) {
  return Object.entries(schema.paths)
    .map(([fieldName, pathType]) => {
      const optional = pathType.isRequired ? '' : '?'
      const tsType = pathToTsType(pathType, `${parentKey}.${fieldName}`)
      return `${fieldName}${optional}: ${tsType}`
    })
    .join('; ')
}

function generateInterfaceSource(fileBaseName, Model) {
  const interfaceName = `I${toPascalCase(fileBaseName)}`
  const lines = Object.entries(Model.schema.paths).map(([fieldName, pathType]) => {
    const optional = pathType.isRequired ? '' : '?'
    const tsType = pathToTsType(pathType, `${fileBaseName}.${fieldName}`)
    return `  ${fieldName}${optional}: ${tsType}`
  })

  return `// AUTO-GENERATED by scripts/generate-types.js from server/model/${fileBaseName}.js
// Do not edit by hand - change the Mongoose schema (or an override in
// scripts/generate-types.js) and re-run \`node scripts/generate-types.js\`.
export interface ${interfaceName} {
${lines.join('\n')}
}
`
}

function run() {
  fs.mkdirSync(OUT_DIR, { recursive: true })

  const files = fs.readdirSync(MODEL_DIR).filter((f) => f.endsWith('.js'))
  const generatedFiles = []

  files.forEach((file) => {
    const fileBaseName = file.replace(/\.js$/, '')
    // eslint-disable-next-line import/no-dynamic-require, global-require
    const mod = require(path.join(MODEL_DIR, file))
    const Model = mod.default || mod

    if (!Model || !Model.schema) {
      console.warn(`generate-types: skipping ${file} - no Mongoose model export found`)
      return
    }

    const source = generateInterfaceSource(fileBaseName, Model)
    const outFile = path.join(OUT_DIR, `${toPascalCase(fileBaseName)}.ts`)
    fs.writeFileSync(outFile, source)
    generatedFiles.push(outFile)
  })

  // Remove stale generated files for models that no longer exist.
  const expected = new Set(generatedFiles.map((f) => path.basename(f)))
  fs.readdirSync(OUT_DIR).forEach((f) => {
    if (!expected.has(f)) fs.unlinkSync(path.join(OUT_DIR, f))
  })

  console.log(`generate-types: wrote ${generatedFiles.length} file(s) to common/types/generated/`)
}

run()
