name: Deploy to study

on:
  push:
    branches: [ "REACT-19" ] # Триггер на пуш в ветку master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_STUDY }}

      - name: Pull changes and restart app
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_STUDY }} << 'EOF'
            cd /root/auto-crm
            git pull
            docker compose build --no-cache
            docker compose up -d --force-recreate
          EOF
